# =============================================================================
# Management: Ansible
# Role:       atc-proxy
# Type:       -
# Author:     awmyhr <awmyhr@gmail.com> (original: Shane McDonald <me@shanemcd.com>)
# Revised:    2020-02-26
# Created:    2020-02-26
# Reference:  https://github.com/shanemcd/ansible-tower-vagrant-cluster/blob/master/provisioning/haproxy.yml
# =============================================================================
---
- hosts: all
  become: yes
  roles:
    - atc-proxy
