# =============================================================================
# Management: Ansible
# Role:       install
# Type:       playbook
# Author:     awmyhr <awmyhr@gmail.com> (original: Shane McDonald <me@shanemcd.com>)
# Revised:    2020-02-27
# Created:    2020-02-27
# Reference:  https://github.com/shanemcd/ansible-tower-vagrant-cluster
# =============================================================================
---

- name: Set up proxy
  hosts: haproxy
  become: yes
  roles:
    - haproxy

- name: Bootstrap
  hosts: all
  become: yes
  tasks:
    - name: Enable scl repo
      yum:
        name: centos-release-scl
        state: installed

- name: Tower install
  hosts: localhost
  tasks:
    - name: Remove previously extracted files
      file:
        path: "{{ playbook_dir }}/setup"
        state: absent

    - name: Download installer
      get_url:
        url: http://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-latest.tar.gz
        dest: "{{ playbook_dir }}"
        mode: 0640
      register: tarball

    - name: Unarchive installer
      unarchive:
        source: "{{ playbook_dir }}/ansible-tower-setup-latest.tar.gz"
        dest: "{{ playbook_dir }}"
